---
title: "Manipulations des métadonnées dans Apogée"
author: "Observatoire de la vie étudiante"
date: "`r format(Sys.Date(), '%d %B %Y')`"
output: 
  rmarkdown::html_vignette:
    number_sections: yes
vignette: >
  %\VignetteIndexEntry{Manipulations des métadonnées dans Apogée}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
library(apogee)
```

# Introduction

La package `apogee` a pour finalité de stocker deux types d'informations à partir du système d'information Apogée :

- D'un côté, les données de scolarité attachées aux étudiants : inscriptions, résultats aux examens, informations individuelles
- De l'autre, l'offre de formation de l'établissement en modélisant les libellés, liens d'historique et de hiérarchie entre les niveaux des formations ainsi que des éléments pédagogiques

Cette vignette a pour but de présenter les données et fonctions stockées dans ce package.

*NB: La procédure d'extraction des données source est réalisée depuis Business Objects (BO) et est décrite dans la vignette [Extraction BO](export_bo.html).*

# Les données

Le package embarque les données

## Les données individuelles et de scolarité

Les données individuelles :

- Individuelles
- Inscription
- Résultats aux examens

### Données individus

La table `individus` :

- état civil
- établissement du baccalaurat

La table `individus_diplome_origine` :

La table `individus_situation_annee_precedente` :

### Données de scolarité UT3

Les tables `inscrits`, `inscrits_annules` et `inscrits_cpge`

La table `inscrits_elp`

La table `inscrits_peda`

La table `resultats_elp`

La table `resultats_etape`

La table `resultats_diplome`

La table `diplomes`

## Les métadonnées

### Offre de formation

#### Composante

Liste des composante de l'université dans les tables suivantes :

- `composante` : libellé, type, localisation
- `composante_histo` : lien de succession entre composantes
- `composante_type` : libellé de type

#### Mention de diplôme

- `mention_diplome` : libellé, année d'activité
- `mention_diplome_histo` : lien de succession entre mentions
- `mention_diplome_lm` : compatibilité entre mentions de Licence et Master

#### Diplôme

Liste des diplômes délivrés à l'université dans les tables suivantes :

- `diplome` : libellé, type, cycle
- `diplome_type` : libellé de type
- `domaine_diplome` : libellé de domaine de diplôme
- `finalite_diplome` : libellé de finalité de diplôme

#### Etape

Liste des années de formation décrites dans les tables suivantes :

- `etape` : libellés, type_diplome, années d'activité
- `etape_composante` : rattachement dans le temps des formations aux composantes
- `etape_domaine` : rattachement des formations aux domaines de diplôme
- `etape_finalite` : correspondance des formation avec la finalité du diplôme (master 2 et diplômes de santé)
- `etape_histo` : lien de succession entre formations
- `etape_mention` : rattachement des formations aux mentions de diplôme
- `etape_secteur` : rattachement des formations aux secteurs définis par le SCUIO-IP
- `etape_sise` : correspondance entre les formations les code diplôme SISE

#### Eléments pédagogiques

- `elp` : 
- `elp_histo` : 
- `elp_nature` : 
- `elp_periode` : 

### Inscription étudiante

- `academie` : 
- `bac` :
- `bac_mention` : 
- `bce_lycees` :
- `bourse` :
- `departement_academie` :
- `diplome_origine_type` : diplôme d'accès à UT3
- `pcs` : 
- `profil_etudiant` : 
- `regime_inscription` : 
- `resultat` : 
- `sexe` : 
- `situation_annee_precedente` : 
- `situation_sociale` : 
- `statut_etudiant` : 

# Les fonctions

Pour manipuler ces données, un ensemble de fonctions ont été codées autour de trois principales fonctionnalités :

- Convertir un code vers son libellé
- Passer dans une hiérarchie d'un niveau de granularité précis vers un niveau plus agrégé
- Pouvoir reconstituer un historique malgré des changement de codification

## Libellés

Préfixe `lib_` et `acronyme_`

- `lib_academie`
- `lib_bac`
- `lib_bourse`
- `lib_composante`
- `lib_cursus_etape` ?
- `lib_diplome`
- `lib_domaine_diplome`
- `lib_elp`
- `lib_etape`
- `lib_finalite_diplome`
- `lib_mention_bac`
- `lib_mention_diplome`
- `lib_nature_elp`
- `lib_pcs`
- `lib_periode_elp`
- `lib_regime_inscription`
- `lib_resultat`
- `lib_sexe`
- `lib_situation_annee_precedente`
- `lib_type_diplome`
- `lib_type_diplome_origine`
- `lib_type_etab`

- `acronyme_bac`
- `acronyme_domaine_diplome`
- `acronyme_etape`
- `acronyme_mention_diplome`
- `acronyme_type_diplome`

## Hiérarchie

Préfixe `hier_`

- `hier_bac_parent`
- `hier_composante_parent`
- `hier_departement_academie`
- `hier_elp_nature`
- `hier_etape_domaine`
- `hier_etape_mention`
- `hier_etape_secteur`
- `hier_etape_type_diplome`
- `hier_mention_parent`
- `hier_pcs_parent`
- `hier_resultat_parent`
- `hier_type_diplome_parent`

## Historique

Préfixe `histo_`

Fonctions successeur `succ`
Fonction prédécesseur `pred`

- `histo_composante_succ`
- `histo_elp_succ`
- `histo_etape_pred`
- `histo_etape_succ`
- `histo_etape_succ_2`
- `histo_mention_diplome_succ`

## Autres fonctions - helpers

- `annee_diplome`
- `annee_en_cours`
- `annee_etape`
- `annee_u`
- `compatibilite_mention_diplome_l`
- `compatibilite_mention_diplome_m`
- `conv_annee_etape_type_diplome`
- `conv_elp_periode`
- `conv_etape_finalite_diplome`
- `conv_etape_sise_diplome`
- `formations_historique`
- `formations_liste`
- `rezip_csv`
- `temoin_etape_actif`
- `temoin_mention_actif`
